name: Creanyx
description: We Blog here!
meta_description: "Creanyx, Expedition to Innovation, SMS, Text messages"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://creanyx.com/blog'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://creanyx.github.io'
author:         'Shakeel Shafiq'
authorDescription:         'Shakeel Shafiq'
